name: CI

on:
  pull_request:
    branches: ["main"]

env:
  NODE_VERSION: 20.8.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Install packages
        run: make install

      - name: Set version info
        id: vars
        run: |
          echo "version_name=ci" >> $GITHUB_OUTPUT
          echo "version_link=https://github.com/danielemery/demery-home" >> $GITHUB_OUTPUT

      - name: Build
        run: make build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          SITE_VERSION_NAME: ${{ steps.vars.outputs.version_name }}
          SITE_VERSION_LINK: ${{ steps.vars.outputs.version_link }}
