name: Deployment

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20.8.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: make install

      - name: Build
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: |
            _site

  staging-deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: static-site
      - name: Sync to S3 staging bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./_site
          destination: s3://${{ vars.AWS_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}

  # production-deployment:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: static-site
  #     - name: Sync to S3 production bucket
  #       uses: keithweaver/aws-s3-github-action@v1.0.0
  #       with:
  #         command: sync
  #         source: ./_site
  #         destination: s3://${{ vars.AWS_BUCKET_NAME }}
  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws_region: ${{ vars.AWS_REGION }}
